# 日志配置
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# 服务器配置
server.port=8080

# 文件路径配置
excel.file.path=username.xlsx

# 留言文件保存路径
message.file.path=D:/work/file/study/git-progranm/personal4/data/messages.txt 